// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -package=dao -destination=mock_client.go
//

// Package dao is a generated GoMock package.
package dao

import (
	reflect "reflect"

	models "github.com/benmatselby/wibble/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDaoClient is a mock of DaoClient interface.
type MockDaoClient struct {
	ctrl     *gomock.Controller
	recorder *MockDaoClientMockRecorder
	isgomock struct{}
}

// MockDaoClientMockRecorder is the mock recorder for MockDaoClient.
type MockDaoClientMockRecorder struct {
	mock *MockDaoClient
}

// NewMockDaoClient creates a new mock instance.
func NewMockDaoClient(ctrl *gomock.Controller) *MockDaoClient {
	mock := &MockDaoClient{ctrl: ctrl}
	mock.recorder = &MockDaoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaoClient) EXPECT() *MockDaoClientMockRecorder {
	return m.recorder
}

// AddArticle mocks base method.
func (m *MockDaoClient) AddArticle(article models.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArticle", article)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddArticle indicates an expected call of AddArticle.
func (mr *MockDaoClientMockRecorder) AddArticle(article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArticle", reflect.TypeOf((*MockDaoClient)(nil).AddArticle), article)
}

// AddFeed mocks base method.
func (m *MockDaoClient) AddFeed(feed models.Feed) (models.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeed", feed)
	ret0, _ := ret[0].(models.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFeed indicates an expected call of AddFeed.
func (mr *MockDaoClientMockRecorder) AddFeed(feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeed", reflect.TypeOf((*MockDaoClient)(nil).AddFeed), feed)
}

// AddTag mocks base method.
func (m *MockDaoClient) AddTag(name string) (models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", name)
	ret0, _ := ret[0].(models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag.
func (mr *MockDaoClientMockRecorder) AddTag(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockDaoClient)(nil).AddTag), name)
}

// AddTagToArticle mocks base method.
func (m *MockDaoClient) AddTagToArticle(articleID, tagID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagToArticle", articleID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTagToArticle indicates an expected call of AddTagToArticle.
func (mr *MockDaoClientMockRecorder) AddTagToArticle(articleID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagToArticle", reflect.TypeOf((*MockDaoClient)(nil).AddTagToArticle), articleID, tagID)
}

// Close mocks base method.
func (m *MockDaoClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDaoClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDaoClient)(nil).Close))
}

// DeleteFeedWithArticles mocks base method.
func (m *MockDaoClient) DeleteFeedWithArticles(feedID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeedWithArticles", feedID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFeedWithArticles indicates an expected call of DeleteFeedWithArticles.
func (mr *MockDaoClientMockRecorder) DeleteFeedWithArticles(feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeedWithArticles", reflect.TypeOf((*MockDaoClient)(nil).DeleteFeedWithArticles), feedID)
}

// DeleteTag mocks base method.
func (m *MockDaoClient) DeleteTag(tagID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockDaoClientMockRecorder) DeleteTag(tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockDaoClient)(nil).DeleteTag), tagID)
}

// GetArticleByID mocks base method.
func (m *MockDaoClient) GetArticleByID(articleID int64) (*models.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleByID", articleID)
	ret0, _ := ret[0].(*models.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleByID indicates an expected call of GetArticleByID.
func (mr *MockDaoClientMockRecorder) GetArticleByID(articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleByID", reflect.TypeOf((*MockDaoClient)(nil).GetArticleByID), articleID)
}

// GetArticlesByFeedID mocks base method.
func (m *MockDaoClient) GetArticlesByFeedID(feedID int64) ([]models.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesByFeedID", feedID)
	ret0, _ := ret[0].([]models.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesByFeedID indicates an expected call of GetArticlesByFeedID.
func (mr *MockDaoClientMockRecorder) GetArticlesByFeedID(feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesByFeedID", reflect.TypeOf((*MockDaoClient)(nil).GetArticlesByFeedID), feedID)
}

// GetArticlesByTagID mocks base method.
func (m *MockDaoClient) GetArticlesByTagID(tagID int64) ([]models.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesByTagID", tagID)
	ret0, _ := ret[0].([]models.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesByTagID indicates an expected call of GetArticlesByTagID.
func (mr *MockDaoClientMockRecorder) GetArticlesByTagID(tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesByTagID", reflect.TypeOf((*MockDaoClient)(nil).GetArticlesByTagID), tagID)
}

// GetFeeds mocks base method.
func (m *MockDaoClient) GetFeeds() ([]models.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeeds")
	ret0, _ := ret[0].([]models.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeeds indicates an expected call of GetFeeds.
func (mr *MockDaoClientMockRecorder) GetFeeds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeeds", reflect.TypeOf((*MockDaoClient)(nil).GetFeeds))
}

// GetTags mocks base method.
func (m *MockDaoClient) GetTags() ([]models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags")
	ret0, _ := ret[0].([]models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockDaoClientMockRecorder) GetTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockDaoClient)(nil).GetTags))
}

// GetTagsForArticle mocks base method.
func (m *MockDaoClient) GetTagsForArticle(articleID int64) ([]models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsForArticle", articleID)
	ret0, _ := ret[0].([]models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsForArticle indicates an expected call of GetTagsForArticle.
func (mr *MockDaoClientMockRecorder) GetTagsForArticle(articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsForArticle", reflect.TypeOf((*MockDaoClient)(nil).GetTagsForArticle), articleID)
}

// MarkArticleAsRead mocks base method.
func (m *MockDaoClient) MarkArticleAsRead(articleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkArticleAsRead", articleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkArticleAsRead indicates an expected call of MarkArticleAsRead.
func (mr *MockDaoClientMockRecorder) MarkArticleAsRead(articleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkArticleAsRead", reflect.TypeOf((*MockDaoClient)(nil).MarkArticleAsRead), articleID)
}

// MarkArticlesAsRead mocks base method.
func (m *MockDaoClient) MarkArticlesAsRead(feedID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkArticlesAsRead", feedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkArticlesAsRead indicates an expected call of MarkArticlesAsRead.
func (mr *MockDaoClientMockRecorder) MarkArticlesAsRead(feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkArticlesAsRead", reflect.TypeOf((*MockDaoClient)(nil).MarkArticlesAsRead), feedID)
}

// RemoveTagFromArticle mocks base method.
func (m *MockDaoClient) RemoveTagFromArticle(articleID, tagID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromArticle", articleID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromArticle indicates an expected call of RemoveTagFromArticle.
func (mr *MockDaoClientMockRecorder) RemoveTagFromArticle(articleID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromArticle", reflect.TypeOf((*MockDaoClient)(nil).RemoveTagFromArticle), articleID, tagID)
}
